site_name: Tinkertoys Documentation
site_description: Comprehensive documentation for tinkertoys utility scripts and automation tools

use_directory_urls: false

nav:
  - Home: index.md
  - Bash Scripts:
    - Overview: bash/overview.md
    - Development Tools:
      - App Builder: bash/development/appifiy.md
      - Folder Comparison: bash/development/comparefolders.md  
      - Image Extension Fixer: bash/development/fixImgExt.md
      - Version Incrementer: bash/development/version_up.md
    - Media Processing:
      - Images to H.264: bash/media/convert_images_to_h264.md
      - Images to ProRes: bash/media/convert_images_to_prores.md
      - Movie to H.264: bash/media/convert_movie_to_h264.md
      - Movie to ProRes: bash/media/convert_movie_to_prores.md
      - Movie to Web: bash/media/movie_to_web.md
      - Stereo Audio Split: bash/media/split_stereo_to_mono.md
    - System Administration:
      - Application List Updater: bash/system/application_list_updater.md
      - Log Size Checker: bash/system/checkLogSize.md
      - Disk Device Finder: bash/system/getDiskDevice.md
      - Memory Purge Loop: bash/system/purgeLoop.md
      - Log Collector: bash/system/log_collector.md
      - Folder Structure Duplicator: bash/system/duplicate_folder_structure.md
    - Rendering Tools:
      - Mail Notifications: bash/rendering/mail_send.md
      - Nuke Render Automation: bash/rendering/nukerender_bash.md
    - Shared Libraries:
      - Common Functions: bash/lib/common.md
      - Media Functions: bash/lib/media_functions.md
      - System Functions: bash/lib/system_functions.md
      - Log and Echo Utils: bash/lib/writeToLogAndEcho.md
  - Python Scripts:
    - Overview: python/overview.md
    - Data Processing:
      - DayOne Journal Splitter: python/data/dayone_split.md
      - Pinboard Export Tool: python/data/export_pinboard.md
      - Render Statistics Analyzer: python/data/renderstats.md
    - Development Tools:
      - Timer Utility: python/development/timer.md
      - Git Empty Folder Marker: python/development/markemptyfolders.md
    - Media Processing:
      - PSD to EXR Converter: python/media/convert_psd_to_exr.md
    - System Utilities:
      - Directory Comparison: python/system/compare_folders.md
      - File Size Comparison: python/system/compare_sizes.md
      - Symlink Repair Tool: python/system/fix_symlinks.md
      - Duplicate File Manager: python/system/keep_larger_version.md
      - Path Replacement Tool: python/system/switch_paths.md
      - Folder Structure Duplicator: python/system/duplicate_folder_structure.md
    - Shared Libraries:
      - AppleScript Integration: python/lib/applescript.md
      - File Copying Utilities: python/lib/copy_file.md
      - Hash Calculation: python/lib/hash_for_file.md
      - Interactive Prompts: python/lib/query_yes_no.md
  - Configuration:
    - Setup Guide: config/setup.md
    - Mail Configuration: config/mail_send.md
    - Log Sources: config/log_sources.md

theme:
  name: "material"
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.indexes
    - search.highlight
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [../python]

markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      permalink: true
  - def_list
  - footnotes
  - md_in_html
